XTRAIN=@XTRAIN@
YTRAIN=@YTRAIN@
LOGLOC=@LOGLOC@
mkdir -p $LOGLOC
MODELLOC=@MODELLOC@
mkdir -p $MODELLOC
ITER=@ITER@
NUCLIDES=@NUCLIDES@
RUN=@RUN@
SEED=@SEED@
NUMTRAIN=@NUMTRAIN@

train_gp_surrogates @NAME@ -x $XTRAIN -y $YTRAIN --log-loc $LOGLOC --model-loc $MODELLOC --max-iter $ITER -i $NUCLIDES -r $RUN -s $SEED -n $NUMTRAIN